# https://docs.marimo.io/guides/publishing/github_pages/#publish-using-github-actions

name: Write HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
    build:
        runs-on: ubuntu-22

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python 3.12
              uses: actions/setup-python@v2
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip setuptools wheel
                pip install --upgrade setuptools
                python -m pip install marimo pints matplotlib numpy

            - name: Export notebook
              run: |
                  marimo export html-wasm pints_demo.py -o output_dir --mode run --no-show-code

            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: output_dir

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            pages: write
            id-token: write

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: github-pages